test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

cloudflare:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  bucket: <%= Rails.application.credentials.dig(:aws, :bucket) %>
  region: auto
  endpoint: <%= Rails.application.credentials.dig(:aws, :endpoint) %>
  force_path_style: true
