# frozen_string_literal: true

if Rails.env.development?
  AdminUser.delete_all
  ActsAsTaggableOn::Tag.destroy_all
  Project.destroy_all
  AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')

  ActsAsTaggableOn::Tag.create!([
                                  { name: "bunny", data: { "stack"=>true, "notable"=>true } },
                                  { name: "haml-rails", data: { "stack"=>true } },
                                  { name: "stripe", data: { "stack"=>true, "notable"=>false } },
                                  { name: "stimulus-rails", data: { "stack"=>true, "notable"=>true } },
                                  { name: "importmap-rails", data: { "stack"=>true, "notable"=>false } },
                                  { name: "rspec-rails", data: { "stack"=>true, "notable"=>true } },
                                  { name: "apartment", data: { "stack"=>true, "notable"=>true } },
                                  { name: "delayed_job_active_record", data: { "stack"=>true } },
                                  { name: "view_component", data: { "stack"=>true, "notable"=>true } },
                                  { name: "liquid", data: { "stack"=>true, "notable"=>false } },
                                  { name: "delayed_job", data: { "stack"=>true } },
                                  { name: "@hotwired/turbo-rails", data: { "stack"=>true, "notable"=>true } },
                                  { name: "mongoid", data: { "stack"=>true, "notable"=>true } },
                                  { name: "react_on_rails", data: { "stack"=>true, "notable"=>true } },
                                  { name: "handlebars", data: { "stack"=>true } },
                                  { name: "elasticsearch", data: { "stack"=>true, "notable"=>true } },
                                  { name: "mysql2", data: { "stack"=>true, "notable"=>false } },
                                  { name: "active_model_serializers", data: { "stack"=>true } },
                                  { name: "parallel_tests", data: { "stack"=>true, "notable"=>true } },
                                  { name: "postcss", data: { "stack"=>true, "notable"=>false } },
                                  { name: "preact", data: { "stack"=>true, "notable"=>true } },
                                  { name: "haml", data: { "stack"=>true, "notable"=>true } },
                                  { name: "stimulus", data: { "stack"=>true, "notable"=>true } },
                                  { name: "bootstrap", data: { "stack"=>true, "notable"=>true } },
                                  { name: "pg", data: { "stack"=>true, "notable"=>false } },
                                  { name: "turbolinks", data: { "stack"=>true, "notable"=>true } },
                                  { name: "elasticsearch-rails", data: { "stack"=>true } },
                                  { name: "elasticsearch-model", data: { "stack"=>true } },
                                  { name: "vue", data: { "stack"=>true, "notable"=>true } },
                                  { name: "backbone", data: { "stack"=>true, "notable"=>true } },
                                  { name: "react", data: { "stack"=>true, "notable"=>true } },
                                  { name: "webpack", data: { "stack"=>true } },
                                  { name: "activemerchant", data: { "stack"=>true } },
                                  { name: "gon", data: { "stack"=>true } },
                                  { name: "coffeescript", data: { "stack"=>true } },
                                  { name: "tailwindcss", data: { "stack"=>true, "notable"=>true } },
                                ])

  prj = Project.create!({
                    name: "Discourse",
                    slug: "discourse",
                    rails_major_version: "5",
                    github: "discourse/discourse",
                    github_about: "A platform for community discussion. Free, open, simple.",
                    website: "http://www.discourse.org",
                    contributors: "1",
                    dependents: "",
                    stars: "33895",
                    watchers: "1",
                    forks: "7344",
                    branch: "main",
                    meta_last_updated_at: "2021-08-26 18:07:14 UTC",
                    description: "next-generation discussion platform",
                    short_blurb: "",
                    last_activity_at: "2021-08-26 17:38:34 UTC",
                    color: "#fbee6a",
                    last_commit: "334ec4edb6e370b880f86baa706ddcfd7fe1d7a2",
                    hidden_at: "",
                    data: {},
                    pulse: "",
                    category_list: ["Forums", "Collaboration"],
                    license_list: ["Other"],
                    adjective_list: [],
                    gem_list: ["actionmailer", "actionpack", "actionview", "activemodel", "activerecord", "activesupport", "railties", "sprockets-rails", "json", "bootsnap", "sprockets", "actionview_precompiler", "seed-fu", "mail", "mini_mime", "mini_suffix", "redis", "redis-namespace", "active_model_serializers", "http_accept_language", "discourse-ember-rails", "discourse-ember-source", "ember-handlebars-template", "discourse-fonts", "barber", "message_bus", "rails_multisite", "fast_xs", "xorcist", "fastimage", "aws-sdk-s3", "aws-sdk-sns", "excon", "unf", "email_reply_trimmer", "image_optim", "multi_json", "mustache", "nokogiri", "loofah", "css_parser", "omniauth", "omniauth-facebook", "omniauth-twitter", "omniauth-github", "omniauth-oauth2", "omniauth-google-oauth2", "oj", "pg", "mini_sql", "pry-rails", "pry-byebug", "r2", "rake", "thor", "diffy", "rinku", "sidekiq", "mini_scheduler", "execjs", "mini_racer", "highline", "rack", "rack-protection", "cbor", "cose", "addressable", "json_schemer", "uglifier", "rtlit", "webmock", "fakeweb", "minitest", "simplecov", "test-prof", "rspec", "mock_redis", "listen", "certified", "fabrication", "mocha", "rb-fsevent", "rspec-rails", "shoulda-matchers", "rspec-html-matchers", "byebug", "rubocop-discourse", "parallel_tests", "rswag-specs", "annotate", "ruby-prof", "bullet", "better_errors", "binding_of_caller", "yaml-lint", "discourse_dev_assets", "faker", "fast_blank", "lru_redux", "htmlentities", "rack-mini-profiler", "unicorn", "puma", "rbtrace", "gc_tracer", "ruby-readability", "stackprof", "memory_profiler", "cppjieba_rb", "lograge", "logstash-event", "logstash-logger", "logster", "sassc", "sassc-rails", "rotp", "rqrcode", "rubyzip", "sshkey", "rchardet", "lz4-ruby", "sanitize", "webpush", "colored2", "maxminddb", "rails_failover"],
                    package_list: ["@fortawesome/fontawesome-free", "@highlightjs/cdn-assets", "@json-editor/json-editor", "@popperjs/core", "@uppy/aws-s3", "@uppy/aws-s3-multipart", "@uppy/core", "@uppy/drop-target", "@uppy/xhr-upload", "ace-builds", "blueimp-file-upload", "bootbox", "bootstrap", "chart.js", "chartjs-plugin-datalabels", "diffhtml", "eslint-config-discourse", "handlebars", "jquery", "jquery-color", "jquery-tags-input", "jquery.autoellipsis", "magnific-popup", "markdown-it", "moment", "moment-timezone", "moment-timezone-names-translations", "mousetrap", "pikaday", "resumablejs", "spectrum-colorpicker", "workbox-cacheable-response", "workbox-core", "workbox-expiration", "workbox-routing", "workbox-strategies", "workbox-sw"],
                    app_directory_list: ["assets", "controllers", "helpers", "jobs", "mailers", "models", "serializers", "services", "views"],
                    backend_stack_list: ["redis", "pg", "sidekiq"],
                    frontend_stack_list: ["bootstrap"],
                  })
  Project.create!({
                    name: "huginn",
                    slug: "huginn",
                    rails_major_version: "5",
                    github: "huginn/huginn",
                    github_about: "Create agents that monitor and act on your behalf.  Your agents are standing by!",
                    website: "",
                    contributors: "1",
                    dependents: "",
                    stars: "32105",
                    watchers: "1",
                    forks: "3055",
                    branch: "master",
                    meta_last_updated_at: "2021-08-28 04:01:38 UTC",
                    description: "open-source IFTTT",
                    short_blurb: "One of my favorite projects. The way they structure their rulesets is awesome and a great example of dynamically building data.",
                    last_activity_at: "2021-04-14 11:19:32 UTC",
                    color: "#972900",
                    last_commit: "1d1243808270e374b7665662952ab473427735b7",
                    hidden_at: "",
                    data: {},
                    pulse: "",
                    category_list: ["Productivity"],
                    license_list: ["MIT License"],
                    adjective_list: [],
                    gem_list: ["dotenv", "dotenv-rails", "twilio-ruby", "ruby-growl", "net-ftp-list", "forecast_io", "rturk", "erector", "hipchat", "mini_racer", "xmpp4r", "mqtt", "slack-notifier", "hypdf", "weibo_2", "google-api-client", "google-cloud-translate", "twitter", "twitter-stream", "omniauth-twitter", "tumblr_client", "omniauth-tumblr", "dropbox-api", "omniauth-dropbox-oauth2", "haversine", "omniauth-evernote", "evernote_oauth", "listen", "aws-sdk-core", "omniauth-37signals", "omniauth-wunderlist", "ace-rails-ap", "bootstrap-kaminari-views", "bundler", "coffee-rails", "daemons", "delayed_job", "delayed_job_active_record", "devise", "em-http-request", "faraday", "faraday_middleware", "feedjira", "font-awesome-sass", "foreman", "geokit", "geokit-rails", "httparty", "httmultiparty", "jquery-rails", "huginn_agent", "json", "jsonpath", "kaminari", "kramdown", "liquid", "loofah", "mini_magick", "multi_xml", "nokogiri", "omniauth", "rails", "sprockets", "rails-html-sanitizer", "rufus-scheduler", "sass-rails", "select2-rails", "spectrum-rails", "execjs", "typhoeus", "uglifier", "bootsnap", "better_errors", "binding_of_caller", "guard", "guard-livereload", "guard-rspec", "rack-livereload", "letter_opener_web", "web-console", "capistrano", "capistrano-rails", "capistrano-bundler", "spring-commands-rspec", "spring", "spring-watcher-listen", "coveralls", "capybara", "capybara-screenshot", "capybara-select-2", "poltergeist", "pry-rails", "pry-byebug", "rr", "rspec", "rspec-rails", "rspec-collection_matchers", "rspec-html-matchers", "rails-controller-testing", "shoulda-matchers", "vcr", "webmock", "unicorn", "ffi", "tzinfo", "tzinfo-data", "rb-kqueue", "pg", "mysql2"],
                    package_list: [],
                    app_directory_list: ["assets", "concerns", "controllers", "helpers", "importers", "jobs", "mailers", "models", "presenters", "validators", "views"],
                    backend_stack_list: ["delayed_job", "delayed_job_active_record", "pg", "mysql2"],
                    frontend_stack_list: [],
                  })
  Project.create!({
                    name: "Mastodon",
                    slug: "mastodon",
                    rails_major_version: "5",
                    github: "mastodon/mastodon",
                    github_about: "Your self-hosted, globally interconnected microblogging community",
                    website: "",
                    contributors: "1",
                    dependents: "",
                    stars: "24649",
                    watchers: "1",
                    forks: "4101",
                    branch: "main",
                    meta_last_updated_at: "2021-08-26 18:05:53 UTC",
                    description: "distributed, interconnected microblogging",
                    short_blurb: "Some really advanced concepts in this codebase if you're interested in distributed systems.",
                    last_activity_at: "2021-08-26 14:51:22 UTC",
                    color: "#686a6c",
                    last_commit: "60af89149d26d049e25dfe829ae54376a873c2b7",
                    hidden_at: "",
                    data: {},
                    pulse: "",
                    category_list: ["Social"],
                    license_list: ["GNU Affero General Public License v3.0"],
                    adjective_list: ["in-production"],
                    gem_list: ["pkg-config", "puma", "rails", "sprockets", "thor", "rack", "hamlit-rails", "pg", "makara", "pghero", "dotenv-rails", "aws-sdk-s3", "fog-core", "fog-openstack", "paperclip", "blurhash", "active_model_serializers", "addressable", "bootsnap", "browser", "charlock_holmes", "iso-639", "chewy", "cld3", "devise", "devise-two-factor", "devise_pam_authenticatable2", "net-ldap", "omniauth-cas", "omniauth-saml", "omniauth", "omniauth-rails_csrf_protection", "color_diff", "discard", "doorkeeper", "ed25519", "fast_blank", "fastimage", "hiredis", "redis-namespace", "htmlentities", "http", "http_accept_language", "httplog", "idn-ruby", "kaminari", "link_header", "mime-types", "nokogiri", "nsa", "oj", "ox", "parslet", "parallel", "posix-spawn", "pundit", "premailer-rails", "rack-attack", "rack-cors", "rails-i18n", "rails-settings-cached", "redis", "mario-redis-lock", "rqrcode", "ruby-progressbar", "sanitize", "scenic", "sidekiq", "sidekiq-scheduler", "sidekiq-unique-jobs", "sidekiq-bulk", "simple-navigation", "simple_form", "sprockets-rails", "stoplight", "strong_migrations", "tty-prompt", "twitter-text", "tzinfo-data", "webpacker", "webpush", "webauthn", "json-ld", "json-ld-preloaded", "rdf-normalize", "fabrication", "fuubar", "i18n-tasks", "pry-byebug", "pry-rails", "rspec-rails", "private_address_check", "capybara", "climate_control", "faker", "microformats", "rails-controller-testing", "rspec-sidekiq", "simplecov", "webmock", "parallel_tests", "rspec_junit_formatter", "active_record_query_trace", "annotate", "better_errors", "binding_of_caller", "bullet", "letter_opener", "letter_opener_web", "memory_profiler", "rubocop", "rubocop-rails", "brakeman", "bundler-audit", "capistrano", "capistrano-rails", "capistrano-rbenv", "capistrano-yarn", "stackprof", "lograge", "concurrent-ruby", "connection_pool", "xorcist"],
                    package_list: ["@babel/core", "@babel/plugin-proposal-decorators", "@babel/plugin-transform-react-inline-elements", "@babel/plugin-transform-runtime", "@babel/preset-env", "@babel/preset-react", "@babel/runtime", "@gamestdio/websocket", "@github/webauthn-json", "@rails/ujs", "array-includes", "arrow-key-navigation", "autoprefixer", "axios", "babel-loader", "babel-plugin-lodash", "babel-plugin-preval", "babel-plugin-react-intl", "babel-plugin-transform-react-remove-prop-types", "babel-runtime", "blurhash", "classnames", "color-blend", "compression-webpack-plugin", "cross-env", "css-loader", "cssnano", "detect-passive-events", "dotenv", "emoji-mart", "es6-symbol", "escape-html", "exif-js", "express", "file-loader", "font-awesome", "glob", "history", "http-link-header", "immutable", "imports-loader", "intersection-observer", "intl", "intl-messageformat", "intl-relativeformat", "is-nan", "js-yaml", "lodash", "mark-loader", "marky", "mini-css-extract-plugin", "mkdirp", "npmlog", "object-assign", "object-fit-images", "object.values", "offline-plugin", "path-complete-extname", "pg", "postcss-loader", "postcss-object-fit-images", "promise.prototype.finally", "prop-types", "punycode", "react", "react-dom", "react-hotkeys", "react-immutable-proptypes", "react-immutable-pure-component", "react-intl", "react-masonry-infinite", "react-motion", "react-notification", "react-overlays", "react-redux", "react-redux-loading-bar", "react-router-dom", "react-router-scroll-4", "react-select", "react-sparklines", "react-swipeable-views", "react-textarea-autosize", "react-toggle", "redis", "redux", "redux-immutable", "redux-thunk", "regenerator-runtime", "rellax", "requestidlecallback", "reselect", "rimraf", "sass", "sass-loader", "stacktrace-js", "stringz", "substring-trie", "terser-webpack-plugin", "tesseract.js", "throng", "tiny-queue", "twitter-text", "uuid", "webpack", "webpack-assets-manifest", "webpack-bundle-analyzer", "webpack-cli", "webpack-merge", "wicg-inert", "ws"],
                    app_directory_list: ["chewy", "controllers", "helpers", "javascript", "lib", "mailers", "models", "policies", "presenters", "serializers", "services", "validators", "views", "workers"],
                    backend_stack_list: ["pg", "redis", "sidekiq", "webpacker"],
                    frontend_stack_list: ["react"],
                  })
  Project.create!({
                    name: "GitLab",
                    slug: "gitlab",
                    rails_major_version: "5",
                    github: "gitlabhq/gitlabhq",
                    github_about: "GitLab CE Mirror | Please open new issues in our issue tracker on GitLab.com",
                    website: "https://about.gitlab.com/",
                    contributors: "1",
                    dependents: "",
                    stars: "22696",
                    watchers: "1",
                    forks: "5674",
                    branch: "master",
                    meta_last_updated_at: "2021-08-26 18:04:33 UTC",
                    description: "self hosted Git management",
                    short_blurb: "",
                    last_activity_at: "2021-08-26 15:10:41 UTC",
                    color: "#f85804",
                    last_commit: "2deb9fe46e598f53762ec39ad927333689144184",
                    hidden_at: "",
                    data: {},
                    pulse: "",
                    category_list: ["Collaboration", "Developers"],
                    license_list: ["Other"],
                    adjective_list: [],
                    gem_list: ["rails", "bootsnap", "responders", "sprockets", "default_value_for", "pg", "rugged", "grape-path-helpers", "faraday", "marginalia", "declarative_policy", "devise", "bcrypt", "doorkeeper", "doorkeeper-openid_connect", "rexml", "ruby-saml", "omniauth", "omniauth-auth0", "omniauth-azure-activedirectory-v2", "omniauth-azure-oauth2", "omniauth-cas3", "omniauth-facebook", "omniauth-github", "omniauth-gitlab", "omniauth-google-oauth2", "omniauth-kerberos", "omniauth-oauth2-generic", "omniauth-saml", "omniauth-shibboleth", "omniauth-twitter", "omniauth_crowd", "omniauth-authentiq", "gitlab-omniauth-openid-connect", "omniauth-salesforce", "omniauth-atlassian-oauth2", "rack-oauth2", "jwt", "gssapi", "recaptcha", "akismet", "invisible_captcha", "devise-two-factor", "rqrcode-rails3", "attr_encrypted", "u2f", "validates_hostname", "rubyzip", "acme-client", "browser", "ohai", "gpgme", "gitlab_omniauth-ldap", "grape-entity", "rack-cors", "graphql", "graphiql-rails", "apollo_upload_server", "graphql-docs", "graphlient", "hashie", "hashie-forbidden_attributes", "kaminari", "hamlit", "carrierwave", "mini_magick", "fog-aws", "fog-core", "fog-google", "fog-local", "fog-openstack", "fog-rackspace", "fog-aliyun", "gitlab-fog-azure-rm", "google-api-client", "unf", "seed-fu", "elasticsearch-model", "elasticsearch-rails", "elasticsearch-api", "aws-sdk-core", "aws-sdk-cloudformation", "aws-sdk-s3", "faraday_middleware-aws-sigv4", "html-pipeline", "deckar01-task_list", "gitlab-markup", "github-markup", "commonmarker", "kramdown", "RedCloth", "rdoc", "org-ruby", "creole", "wikicloth", "asciidoctor", "asciidoctor-include-ext", "asciidoctor-plantuml", "asciidoctor-kroki", "rouge", "truncato", "bootstrap_form", "nokogiri", "escape_utils", "icalendar", "diffy", "diff_match_patch", "rack", "rack-timeout", "puma", "puma_worker_killer", "state_machines-activerecord", "acts-as-taggable-on", "sidekiq", "sidekiq-cron", "redis-namespace", "gitlab-sidekiq-fetcher", "fugit", "httparty", "rainbow", "ruby-progressbar", "settingslogic", "re2", "version_sorter", "js_regex", "device_detector", "redis", "connection_pool", "redis-rails", "discordrb-webhooks", "jira-ruby", "atlassian-jwt", "flowdock", "slack-messenger", "hangouts-chat", "asana", "ruby-fogbugz", "kubeclient", "sanitize", "babosa", "loofah", "licensee", "charlock_holmes", "ruby-magic", "fast_blank", "gitlab-chronic", "gitlab_chronic_duration", "rack-proxy", "sassc-rails", "autoprefixer-rails", "terser", "addressable", "gemojione", "gon", "request_store", "base32", "gitlab-license", "rack-attack", "sentry-raven", "pg_query", "premailer-rails", "gitlab-labkit", "thrift", "ruby_parser", "rails-i18n", "gettext_i18n_rails", "gettext_i18n_rails_js", "gettext", "batch-loader", "peek", "snowplow-tracker", "method_source", "webrick", "prometheus-client-mmap", "warning", "lefthook", "solargraph", "letter_opener_web", "better_errors", "thin", "deprecation_toolkit", "bullet", "pry-byebug", "pry-rails", "pry-shell", "awesome_print", "database_cleaner", "factory_bot_rails", "rspec-rails", "minitest", "ffaker", "spring", "spring-commands-rspec", "gitlab-styles", "haml_lint", "bundler-audit", "benchmark-ips", "knapsack", "crystalball", "simple_po_parser", "timecop", "png_quantizator", "parallel", "rblineprof", "test_file_finder", "gitlab-dangerfiles", "simplecov", "simplecov-cobertura", "license_finder", "fuubar", "rspec-retry", "rspec_profiling", "rspec-parameterized", "capybara", "capybara-screenshot", "selenium-webdriver", "shoulda-matchers", "email_spec", "webmock", "rails-controller-testing", "concurrent-ruby", "test-prof", "rspec_junit_formatter", "guard-rspec", "derailed_benchmarks", "octokit", "gitlab-mail_room", "email_reply_trimmer", "html2text", "ruby-prof", "stackprof", "rbtrace", "memory_profiler", "benchmark-memory", "activerecord-explain-analyze", "oauth2", "health_check", "vmstat", "sys-filesystem", "net-ntp", "net-ssh", "sshkey", "ed25519", "bcrypt_pbkdf", "spamcheck", "gitaly", "kas-grpc", "grpc", "google-protobuf", "toml-rb", "flipper", "flipper-active_record", "flipper-active_support_cache_store", "unleash", "gitlab-experiment", "lograge", "grape_logging", "gitlab-net-dns", "countries", "retriable", "lru_redux", "erubi", "mail", "mail-smtp_pool", "lockbox", "valid_email", "json", "json_schemer", "oj", "multi_json", "yajl-ruby", "webauthn", "ipaddress", "parslet", "net-ldap", "grape"],
                    package_list: ["@babel/core", "@babel/plugin-proposal-class-properties", "@babel/plugin-proposal-json-strings", "@babel/plugin-proposal-private-methods", "@babel/plugin-syntax-import-meta", "@babel/preset-env", "@gitlab/at.js", "@gitlab/favicon-overlay", "@gitlab/svgs", "@gitlab/tributejs", "@gitlab/ui", "@gitlab/visual-review-tools", "@rails/actioncable", "@rails/ujs", "@sentry/browser", "@sourcegraph/code-host-integration", "@tiptap/core", "@tiptap/extension-blockquote", "@tiptap/extension-bold", "@tiptap/extension-bullet-list", "@tiptap/extension-code", "@tiptap/extension-code-block-lowlight", "@tiptap/extension-document", "@tiptap/extension-dropcursor", "@tiptap/extension-gapcursor", "@tiptap/extension-hard-break", "@tiptap/extension-heading", "@tiptap/extension-history", "@tiptap/extension-horizontal-rule", "@tiptap/extension-image", "@tiptap/extension-italic", "@tiptap/extension-link", "@tiptap/extension-list-item", "@tiptap/extension-ordered-list", "@tiptap/extension-paragraph", "@tiptap/extension-strike", "@tiptap/extension-subscript", "@tiptap/extension-superscript", "@tiptap/extension-table", "@tiptap/extension-table-cell", "@tiptap/extension-table-header", "@tiptap/extension-table-row", "@tiptap/extension-task-item", "@tiptap/extension-task-list", "@tiptap/extension-text", "@tiptap/vue-2", "@toast-ui/editor", "@toast-ui/vue-editor", "apollo-cache-inmemory", "apollo-client", "apollo-link", "apollo-link-batch-http", "apollo-link-http", "apollo-upload-client", "autosize", "aws-sdk", "axios", "babel-loader", "babel-plugin-lodash", "bootstrap", "cache-loader", "clipboard", "codemirror", "codesandbox-api", "compression-webpack-plugin", "copy-webpack-plugin", "core-js", "cron-validator", "cropper", "css-loader", "d3", "d3-sankey", "d3-selection", "dateformat", "deckar01-task_list", "diff", "dompurify", "dropzone", "editorconfig", "emoji-regex", "emoji-unicode-version", "fast-mersenne-twister", "file-loader", "fuzzaldrin-plus", "graphql", "graphql-tag", "immer", "ipaddr.js", "jed", "jquery", "jquery.caret", "js-cookie", "js-yaml", "jszip", "jszip-utils", "katex", "lodash", "lowlight", "marked", "mathjax", "mermaid", "minimatch", "monaco-editor", "monaco-editor-webpack-plugin", "monaco-yaml", "mousetrap", "papaparse", "pdfjs-dist", "pikaday", "popper.js", "portal-vue", "prismjs", "prosemirror-inputrules", "prosemirror-markdown", "prosemirror-model", "prosemirror-state", "prosemirror-tables", "raphael", "raw-loader", "scrollparent", "select2", "smooshpack", "sortablejs", "sql.js", "string-hash", "style-loader", "swagger-ui-dist", "three", "three-orbit-controls", "three-stl-loader", "timeago.js", "tiptap", "tiptap-extensions", "url-loader", "uuid", "visibilityjs", "vue", "vue-apollo", "vue-loader", "vue-observe-visibility", "vue-resize", "vue-router", "vue-template-compiler", "vue-virtual-scroll-list", "vuedraggable", "vuex", "web-vitals", "webpack", "webpack-bundle-analyzer", "webpack-cli", "webpack-stats-plugin", "worker-loader", "xterm"],
                    app_directory_list: ["assets", "channels", "controllers", "enums", "experiments", "finders", "graphql", "helpers", "mailers", "models", "policies", "presenters", "serializers", "services", "uploaders", "validators", "views", "workers"],
                    backend_stack_list: ["pg", "graphql", "elasticsearch-rails", "sidekiq", "redis", "flipper", "grape"],
                    frontend_stack_list: ["bootstrap", "vue"],
                  })
  Project.create!({
                    name: "forem",
                    slug: "forem-forem",
                    rails_major_version: "5",
                    github: "forem/forem",
                    github_about: "For empowering community 🌱",
                    website: "",
                    contributors: "1",
                    dependents: "",
                    stars: "17333",
                    watchers: "1",
                    forks: "3029",
                    branch: "main",
                    meta_last_updated_at: "2021-08-28 04:03:05 UTC",
                    description: "the platform that powers dev.to",
                    short_blurb: "Well-organized with great abstractions make this codebase pleasant to read.",
                    last_activity_at: "2021-08-27 23:21:07 UTC",
                    color: "#333333",
                    last_commit: "0d7494c0e315732fcb514698ccc9bd674a341040",
                    hidden_at: "",
                    data: {},
                    pulse: "",
                    category_list: ["Social"],
                    license_list: ["GNU Affero General Public License v3.0"],
                    adjective_list: ["in-production"],
                    gem_list: ["hypershield", "nakayoshi_fork", "rack-host-redirect", "active_record_union", "acts-as-taggable-on", "acts_as_follower", "addressable", "ahoy_email", "ahoy_matey", "ancestry", "blazer", "bootsnap", "carrierwave", "carrierwave-bombshelter", "cloudinary", "counter_culture", "ddtrace", "devise", "devise_invitable", "dogstatsd-ruby", "doorkeeper", "email_validator", "emoji_regex", "fastimage", "fastly", "feedjira", "field_test", "flipper", "flipper-active_record", "flipper-ui", "fog-aws", "front_matter_parser", "gemoji", "gibbon", "hairtrigger", "honeybadger", "honeycomb-beeline", "html_truncator", "htmlentities", "httparty", "imgproxy", "inline_svg", "jbuilder", "jsonapi-serializer", "kaminari", "katex", "liquid", "nokogiri", "octokit", "oj", "omniauth", "omniauth-apple", "omniauth-facebook", "omniauth-github", "omniauth-rails_csrf_protection", "omniauth-twitter", "parallel", "patron", "pg", "pg_search", "puma", "pundit", "pusher", "rack-attack", "rack-cors", "rack-timeout", "rails", "rss", "rails-settings-cached", "ransack", "recaptcha", "redcarpet", "redis", "rpush", "rpush-redis", "redis-actionpack", "redis-rack", "redis-rails", "request_store", "reverse_markdown", "rolify", "rouge", "rubyzip", "s3_direct_upload", "sidekiq", "sidekiq-cron", "sidekiq-unique-jobs", "sitemap_generator", "slack-notifier", "sprockets", "staccato", "store_attribute", "storext", "stripe", "strong_migrations", "twitter", "uglifier", "ulid", "validate_url", "vault", "view_component", "wcag_color_contrast", "webpacker", "better_errors", "brakeman", "bundler-audit", "derailed_benchmarks", "erb_lint", "guard", "guard-livereload", "listen", "memory_profiler", "web-console", "amazing_print", "bullet", "capybara", "cypress-rails", "dotenv-rails", "faker", "knapsack_pro", "pry", "pry-rails", "rspec-rails", "rubocop", "rubocop-performance", "rubocop-rails", "rubocop-rspec", "sassc-rails", "spring", "spring-commands-rspec", "exifr", "factory_bot_rails", "fakeredis", "launchy", "pundit-matchers", "rspec-retry", "ruby-prof", "shoulda-matchers", "simplecov", "stackprof", "stripe-ruby-mock", "test-prof", "timecop", "vcr", "webdrivers", "webmock", "zonebie"],
                    package_list: ["@babel/core", "@babel/plugin-proposal-class-properties", "@babel/plugin-syntax-dynamic-import", "@babel/plugin-transform-react-jsx", "@babel/preset-env", "@github/clipboard-copy-element", "@github/time-elements", "@honeybadger-io/webpack", "@rails/ujs", "@rails/webpacker", "@reach/combobox", "ahoy.js", "autoprefixer", "babel-preset-preact", "canvas", "chart.js", "clipboard-polyfill", "core-js", "file-loader", "focus-trap", "focus-visible", "he", "honeybadger-js", "intersection-observer", "linkstate", "lodash.debounce", "postcss", "postcss-cli", "postcss-cssnext", "postcss-smart-import", "postscribe", "preact", "prop-types", "pusher-js", "rails-erb-loader", "stimulus", "web-share-wrapper"],
                    app_directory_list: ["assets", "black_box", "components", "controllers", "decorators", "errors", "helpers", "javascript", "lib", "liquid_tags", "mailers", "models", "policies", "queries", "refinements", "sanitizers", "serializers", "services", "uploaders", "validators", "view_objects", "views", "workers"],
                    backend_stack_list: ["flipper", "pg", "pg_search", "redis", "sidekiq", "webpacker"],
                    frontend_stack_list: ["preact", "stimulus"],
                  })
  Project.create!({
                    name: "Diaspora",
                    slug: "diaspora",
                    rails_major_version: "5",
                    github: "diaspora/diaspora",
                    github_about: "A privacy-aware, distributed, open source social network.",
                    website: "https://diasporafoundation.org",
                    contributors: "1",
                    dependents: "",
                    stars: "12792",
                    watchers: "1",
                    forks: "2924",
                    branch: "develop",
                    meta_last_updated_at: "2021-08-26 18:05:12 UTC",
                    description: "community-run, distributed social-network",
                    short_blurb: "",
                    last_activity_at: "2021-08-15 23:02:28 UTC",
                    color: "#000000",
                    last_commit: "38c686c66e61bdbd141d32d898dd1c0d4d162db8",
                    hidden_at: "",
                    data: {},
                    pulse: "",
                    category_list: ["Social", "Microblogging"],
                    license_list: ["Other"],
                    adjective_list: [],
                    gem_list: ["rails", "responders", "unicorn", "unicorn-worker-killer", "diaspora_federation-json_schema", "diaspora_federation-rails", "acts_as_api", "json", "json-schema", "yajl-ruby", "devise", "devise_lastseenable", "devise-two-factor", "rqrcode", "simple_captcha2", "redis", "sidekiq", "sidekiq-cron", "terser", "configurate", "toml-rb", "rack-cors", "autoprefixer-rails", "bootstrap-sass", "bootstrap-switch-rails", "compass-rails", "sass-rails", "sprockets-rails", "mysql2", "pg", "activerecord-import", "carrierwave", "fog-aws", "mini_magick", "uuid", "entypo-rails", "handlebars_assets", "jquery-rails", "jquery-ui-rails", "js-routes", "js_image_paths", "sprockets-es6", "rails-assets-jquery", "rails-assets-highlightjs", "rails-assets-markdown-it", "rails-assets-markdown-it-hashtag", "rails-assets-markdown-it-diaspora-mention", "rails-assets-markdown-it-sanitizer", "rails-assets-markdown-it--markdown-it-for-inline", "rails-assets-markdown-it-sub", "rails-assets-markdown-it-sup", "rails-assets-backbone", "rails-assets-bootstrap-markdown", "rails-assets-corejs-typeahead", "rails-assets-cropperjs", "rails-assets-fine-uploader", "rails-assets-pica", "rails-assets-autosize", "rails-assets-blueimp-gallery", "rails-assets-jquery.are-you-sure", "rails-assets-jquery-placeholder", "rails-assets-jquery-textchange", "rails-assets-utatti-perfect-scrollbar", "markdown-it-html5-embed", "http_accept_language", "i18n-inflector-rails", "rails-i18n", "markerb", "leaflet-rails", "nokogiri", "open_graph_reader", "redcarpet", "ruby-oembed", "twitter-text", "string-direction", "secure_headers", "omniauth", "omniauth-tumblr", "omniauth-twitter", "omniauth-wordpress", "twitter", "openid_connect", "active_model_serializers", "acts-as-taggable-on", "addressable", "faraday", "faraday_middleware", "faraday-cookie_jar", "typhoeus", "gon", "hamlit", "mobile-fu", "rails-timeago", "will_paginate", "logging-rails", "rubyzip", "minitest", "versionist", "rack-google-analytics", "rack-piwik", "eye", "rack-rewrite", "rack-ssl", "asset_sync", "haml_lint", "pronto", "pronto-eslint", "pronto-haml", "pronto-rubocop", "pronto-scss", "rubocop", "rubocop-rails", "pry", "pry-byebug", "simplecov", "turbo_dev_assets", "listen", "fixture_builder", "fuubar", "json-schema-rspec", "rspec-json_expectations", "apparition", "capybara", "database_cleaner-active_record", "cucumber-api-steps", "factory_bot_rails", "shoulda-matchers", "timecop", "webmock", "diaspora_federation-test", "rspec-rails", "cucumber-rails", "chrome_remote", "jasmine", "jasmine-jquery-rails", "rails-assets-jasmine-ajax", "sinon-rails", "rails-controller-testing"],
                    package_list: [],
                    app_directory_list: ["assets", "controllers", "helpers", "mailers", "models", "presenters", "serializers", "services", "uploaders", "views", "workers"],
                    backend_stack_list: ["redis", "sidekiq", "mysql2", "pg"],
                    frontend_stack_list: [],
                  })
  Project.create!({
                    name: "spree",
                    slug: "spree",
                    rails_major_version: "5",
                    github: "spree/spree",
                    github_about: "Open Source modular headless multi-language/multi-currency/multi-store e-commerce platform",
                    website: "",
                    contributors: "1",
                    dependents: "",
                    stars: "11380",
                    watchers: "1",
                    forks: "4779",
                    branch: "main",
                    meta_last_updated_at: "2021-08-28 04:01:02 UTC",
                    description: "a flexible e-commerce platform",
                    short_blurb: "Because you definitely don't want to build your own e-commerce setup, Spree exists.",
                    last_activity_at: "2021-08-27 19:16:22 UTC",
                    color: "#022f66",
                    last_commit: "e92c511c77195f831cd921004ebbc70b6298b54f",
                    hidden_at: "",
                    data: {},
                    pulse: "",
                    category_list: ["E-Commerce", "Rails Engine", "Business"],
                    license_list: ["Other"],
                    adjective_list: [],
                    gem_list: ["spree_core", "spree_api"],
                    package_list: [],
                    app_directory_list: [],
                    backend_stack_list: [],
                    frontend_stack_list: [],
                  })
  Project.create!({
                    name: "Postal",
                    slug: "postal",
                    rails_major_version: "5",
                    github: "postalserver/postal",
                    github_about: "✉️ A fully featured open source mail delivery platform for incoming & outgoing e-mail",
                    website: "",
                    contributors: "1",
                    dependents: "",
                    stars: "10684",
                    watchers: "1",
                    forks: "747",
                    branch: "main",
                    meta_last_updated_at: "2021-08-26 18:06:15 UTC",
                    description: "mail delivery platform for incoming and outgoing e-mail",
                    short_blurb: "Another system for running your own mail service to free yourself from corporate email providers.",
                    last_activity_at: "2021-08-03 10:40:40 UTC",
                    color: "#ff9d00",
                    last_commit: "def3f2e4229d3ab458b0b9900d7f12343f271d5b",
                    hidden_at: "",
                    data: {},
                    pulse: "",
                    category_list: ["Developers", "Email"],
                    license_list: ["MIT License"],
                    adjective_list: ["in-production"],
                    gem_list: ["rails", "mysql2", "puma", "turbolinks", "haml", "nifty-utils", "nilify_blanks", "kaminari", "bcrypt", "foreman", "hashie", "authie", "dynamic_form", "changey", "mail", "autoprefixer-rails", "bunny", "secure_headers", "chronic", "basic_ssl", "clockwork", "encrypto_signo", "nio4r", "mongo", "sentry-raven", "gelf", "moonrope", "jwt", "highline", "resolv", "sass-rails", "uglifier", "coffee-rails", "jquery-rails", "byebug", "annotate", "rspec", "rspec-rails", "factory_bot_rails", "database_cleaner"],
                    package_list: [],
                    app_directory_list: ["assets", "controllers", "helpers", "jobs", "mailers", "models", "views"],
                    backend_stack_list: ["mysql2", "bunny"],
                    frontend_stack_list: [],
                  })
  Project.create!({
                    name: "Chatwoot",
                    slug: "chatwoot",
                    rails_major_version: "5",
                    github: "chatwoot/chatwoot",
                    github_about: "Open-source customer engagement suite, an alternative to Intercom, Zendesk, Salesforce Service Cloud etc. 🔥💬",
                    website: "",
                    contributors: "1",
                    dependents: "",
                    stars: "9992",
                    watchers: "1",
                    forks: "1161",
                    branch: "develop",
                    meta_last_updated_at: "2021-08-26 18:04:28 UTC",
                    description: "customer engagement platform",
                    short_blurb: "Originally abandonware, the Chatwoot team posted on HackerNews and received warm reception. They've since taken off and received funding for their open-source helpdesk and engagement platform. Heavy on front-end frameworks, definitely worth a look!",
                    last_activity_at: "2021-08-26 14:21:10 UTC",
                    color: "#1062eb",
                    last_commit: "06630a8981430714663a4baec9aa73111284c741",
                    hidden_at: "",
                    data: {},
                    pulse: "",
                    category_list: ["Helpdesk", "Startup"],
                    license_list: ["MIT License"],
                    adjective_list: ["professional", "in-production"],
                    gem_list: ["rack-cors", "rails", "bootsnap", "acts-as-taggable-on", "attr_extras", "browser", "hashie", "jbuilder", "kaminari", "responders", "rest-client", "telephone_number", "time_diff", "tzinfo-data", "valid_email2", "uglifier", "flag_shih_tzu", "haikunator", "liquid", "commonmarker", "json_schemer", "rack-attack", "down", "aws-sdk-s3", "azure-storage-blob", "google-cloud-storage", "image_processing", "groupdate", "pg", "redis", "redis-namespace", "activerecord-import", "dotenv-rails", "foreman", "puma", "rack-timeout", "webpacker", "barnes", "devise", "devise-secure_password", "devise_token_auth", "jwt", "pundit", "administrate", "wisper", "facebook-messenger", "telegram-bot-ruby", "twilio-ruby", "twitty", "koala", "slack-ruby-client", "google-cloud-dialogflow", "brakeman", "ddtrace", "newrelic_rpm", "scout_apm", "sentry-rails", "sentry-ruby", "sentry-sidekiq", "sidekiq", "sidekiq-cron", "fcm", "webpush", "geocoder", "maxminddb", "hairtrigger", "procore-sift", "annotate", "bullet", "letter_opener", "web-console", "json_refs", "squasher", "cypress-on-rails", "database_cleaner", "active_record_query_trace", "bundle-audit", "byebug", "factory_bot_rails", "faker", "listen", "mock_redis", "pry-rails", "rspec-rails", "rubocop", "rubocop-performance", "rubocop-rails", "rubocop-rspec", "seed_dump", "shoulda-matchers", "simplecov", "spring", "spring-watcher-listen", "webmock"],
                    package_list: ["@braid/vue-formulate", "@chatwoot/prosemirror-schema", "@chatwoot/utils", "@rails/actioncable", "@rails/webpacker", "@sentry/tracing", "@sentry/vue", "axios", "babel-plugin-syntax-jsx", "babel-plugin-transform-vue-jsx", "bourbon", "chart.js", "copy-text-to-clipboard", "core-js", "country-code-emoji", "date-fns", "dompurify", "dotenv", "foundation-sites", "highlight.js", "ionicons", "js-cookie", "lodash.groupby", "marked", "md5", "prosemirror-markdown", "prosemirror-state", "prosemirror-view", "query-string", "semver", "spinkit", "tailwindcss", "tween.js", "url-loader", "v-tooltip", "vue", "vue-axios", "vue-chartjs", "vue-clickaway", "vue-color", "vue-easytable", "vue-i18n", "vue-loader", "vue-multiselect", "vue-router", "vue-template-compiler", "vue-upload-component", "vue2-datepicker", "vuelidate", "vuex", "vuex-router-sync"],
                    app_directory_list: ["actions", "assets", "builders", "channels", "controllers", "dashboards", "dispatchers", "drops", "fields", "finders", "helpers", "javascript", "jobs", "listeners", "mailboxes", "mailers", "models", "policies", "presenters", "services", "views", "workers"],
                    backend_stack_list: ["pg", "redis", "webpacker", "sidekiq"],
                    frontend_stack_list: ["tailwindcss", "vue"],
                  })
  Project.create!({
                    name: "OpenProject",
                    slug: "openproject",
                    rails_major_version: "5",
                    github: "opf/openproject",
                    github_about: "OpenProject is the leading open source project management software.",
                    website: "",
                    contributors: "1",
                    dependents: "",
                    stars: "5096",
                    watchers: "1",
                    forks: "1475",
                    branch: "dev",
                    meta_last_updated_at: "2021-08-28 04:00:56 UTC",
                    description: "project management system",
                    short_blurb: "",
                    last_activity_at: "2021-08-28 03:12:21 UTC",
                    color: "#02225d",
                    last_commit: "36ff3ed406011eed505385e7d14826f9cd5c0478",
                    hidden_at: "",
                    data: {},
                    pulse: "",
                    category_list: ["Collaboration", "Developers", "Project Management"],
                    license_list: [],
                    adjective_list: [],
                    gem_list: ["warden-basic_auth", "will_paginate", "friendly_id", "acts_as_list", "acts_as_tree", "awesome_nested_set", "rubytree", "typed_dag", "addressable", "auto_strip_attributes", "tzinfo-data", "htmldiff", "stringex", "commonmarker", "html-pipeline", "deckar01-task_list", "escape_utils", "rouge", "sanitize", "rinku", "semantic", "svg-graph", "date_validator", "email_validator", "ruby-duration", "sys-filesystem", "posix-spawn", "bcrypt", "multi_json", "oj", "daemons", "delayed_cron_job", "delayed_job_active_record", "rack-protection", "rack-attack", "secure_headers", "browser", "okcomputer", "gon", "lograge", "structured_warnings", "airbrake", "prawn", "prawn-markup", "cells-erb", "cells-rails", "meta-tags", "dalli", "unicorn-worker-killer", "i18n-js", "rails-i18n", "sprockets", "unicorn", "puma", "nokogiri", "carrierwave", "carrierwave_direct", "fog-aws", "aws-sdk-core", "aws-sdk-s3", "openproject-token", "plaintext", "rest-client", "ruby-progressbar", "mini_magick", "sentry-delayed_job", "sentry-rails", "sentry-ruby", "launchy", "rack-test", "shoulda-context", "test-prof", "database_cleaner", "rack_session_access", "rspec", "rspec-rails", "retriable", "rspec-retry", "compare-xml", "rails-controller-testing", "capybara", "capybara-screenshot", "selenium-webdriver", "webdrivers", "fuubar", "timecop", "webmock", "puffing-billy", "table_print", "equivalent-xml", "json_spec", "shoulda-matchers", "parallel_tests", "net-ldap", "listen", "faker", "letter_opener", "spring", "spring-commands-rspec", "rubocop", "rubocop-rails", "rubocop-rspec", "livingstyleguide", "sassc-rails", "factory_bot", "factory_bot_rails", "flamegraph", "rack-mini-profiler", "ruby-prof", "stackprof", "pry-byebug", "pry-rails", "pry-rescue", "pry-stack_explorer", "brakeman", "danger-brakeman", "bootsnap", "grape", "roar", "rack-cors", "disposable", "pg", "activerecord-nulldb-adapter", "with_advisory_lock", "openproject-translations", "actionpack-xml_parser", "activemodel-serializers-xml", "activerecord-import", "activerecord-session_store", "rails", "responders", "rdoc", "doorkeeper", "omniauth", "request_store", "warden"],
                    package_list: [],
                    app_directory_list: ["assets", "cells", "contracts", "controllers", "helpers", "mailers", "models", "policies", "seeders", "services", "uploaders", "validators", "views", "workers"],
                    backend_stack_list: ["delayed_job_active_record", "grape", "pg"],
                    frontend_stack_list: [],
                  })
  Project.create!({
                    name: "Solidus",
                    slug: "solidus",
                    rails_major_version: "5",
                    github: "solidusio/solidus",
                    github_about: "🛒Solidus, Rails eCommerce System",
                    website: "https://solidus.io/",
                    contributors: "1",
                    dependents: "",
                    stars: "3829",
                    watchers: "131",
                    forks: "1094",
                    branch: "master",
                    meta_last_updated_at: "2021-08-29 20:07:31 UTC",
                    description: "e-commerce system",
                    short_blurb: "",
                    last_activity_at: "2021-08-09 09:21:47 UTC",
                    color: "#040507",
                    last_commit: "75c23a20a2761ea5f1d2d8cda749ef75b636d269",
                    hidden_at: "",
                    data: { gems_path: "core/solidus_core.gemspec" },
                    pulse: "",
                    category_list: ["E-Commerce"],
                    license_list: ["Other"],
                    adjective_list: [],
                    gem_list: ["activemerchant", "acts_as_list", "awesome_nested_set", "cancancan", "carmen", "discard", "friendly_id", "image_processing", "kaminari-activerecord", "mini_magick", "monetize", "kt-paperclip", "ransack", "state_machines-activerecord"],
                    package_list: [],
                    app_directory_list: [],
                    backend_stack_list: [],
                    frontend_stack_list: [],
                  })


end
